## Preliminary Sales Analysis

**Notebook Scope:**

**Inputs:**
Los datos a utilizar seran los provistos por la compañia en su base de datos AYN SALES DB.

**Process**
El objetivo de este analisis es buscar insights que expliquen el desempeño de las ventas de la compañia.

**Outputs**
Nuevas features

**Notebook Schema:**

* *Feature Analysis* | El objetivo es analizar preliminarmente los features.

## Feature Analysis

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import data_loader_module

### Loading the data

In [2]:
# path of data on drive
file_path = "C:\\Users\\Alejandro\\Desktop\\Alpha Project\\Code\\Supermarket_challenge\\Data_future_sales\\new_datasets\\dict_dfs_eda"

# Load python object using a local module
dict_mod_df = data_loader_module.load_pickle_file(file_path=file_path)

The file has been readed from the following path: C:\Users\Alejandro\Desktop\Alpha Project\Code\Supermarket_challenge\Data_future_sales\new_datasets\dict_dfs_eda

In [3]:
dict_mod_df["sales_df"].head(1)

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day,shop_name,item_name,item_category_id,item_category_name,market_category,item_category,year,month
0,2013-01-02,0,59,22154,999.0,1.0,"Yaroslavl shopping center ""Altair""",PHENOMENON 2012 (BD),37,Cinema - Blu-Ray,Cinema,Blu-Ray,2013,1

### Some comments regarding the data.

Como se puede visualizar en el dataset, la tienda solo almacena los siguientes eventos de sus ventas.
* Fechas
* Items
* Cantidades
* Precios
* Tiendas

En base a ello se desprenden diferentes datos obtenidos de cada una.

**Fechas:**
- date -> fecha
- date_block_num -> semana del año
- year -> año
- month -> mes del año en formato numerico

**Items:**

* *Originales:*

    - item_name ->
    - item_category_name ->
    - item_id
    - item_category_id
    
* *Artificiales:*

    - market_category -> Categoria de mercado de los items vendidos
    - item_category -> Categoria del item


**Cantidades:**
- item_cnt_day -> cantidad vendida


**Price:**
- item_price


**locations**
- Shops

### Basic Analysis

In [4]:
dict_mod_df["sales_df"]

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day,shop_name,item_name,item_category_id,item_category_name,market_category,item_category,year,month
0,2013-01-02,0,59,22154,999.0,1.0,"Yaroslavl shopping center ""Altair""",PHENOMENON 2012 (BD),37,Cinema - Blu-Ray,Cinema,Blu-Ray,2013,1
1,2013-01-02,0,25,22154,999.0,1.0,"Moscow TRK ""Atrium""",PHENOMENON 2012 (BD),37,Cinema - Blu-Ray,Cinema,Blu-Ray,2013,1
2,2013-01-03,0,25,22154,999.0,1.0,"Moscow TRK ""Atrium""",PHENOMENON 2012 (BD),37,Cinema - Blu-Ray,Cinema,Blu-Ray,2013,1
3,2013-01-20,0,25,22154,999.0,1.0,"Moscow TRK ""Atrium""",PHENOMENON 2012 (BD),37,Cinema - Blu-Ray,Cinema,Blu-Ray,2013,1
4,2013-01-23,0,25,22154,999.0,1.0,"Moscow TRK ""Atrium""",PHENOMENON 2012 (BD),37,Cinema - Blu-Ray,Cinema,Blu-Ray,2013,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2935844,2015-10-22,33,55,13093,250.0,1.0,Digital warehouse 1C-Online,Windows Payment Card: 250 rubles [Digital vers...,36,Payment Cards - Windows (Digital),Payment Cards,Windows (Digital),2015,10
2935845,2015-09-21,32,55,13091,1000.0,1.0,Digital warehouse 1C-Online,Windows Payment Card: 1000 rubles [Digital ver...,36,Payment Cards - Windows (Digital),Payment Cards,Windows (Digital),2015,9
2935846,2015-09-16,32,55,13094,2500.0,1.0,Digital warehouse 1C-Online,Windows Payment Card: 2500 rubles [Digital ver...,36,Payment Cards - Windows (Digital),Payment Cards,Windows (Digital),2015,9
2935847,2015-09-22,32,55,13094,2500.0,2.0,Digital warehouse 1C-Online,Windows Payment Card: 2500 rubles [Digital ver...,36,Payment Cards - Windows (Digital),Payment Cards,Windows (Digital),2015,9
2935848,2015-10-26,33,55,13092,2000.0,1.0,Digital warehouse 1C-Online,Windows payment card: 2000 rubles [Digital ver...,36,Payment Cards - Windows (Digital),Payment Cards,Windows (Digital),2015,10

### Split the test set

In [5]:
dict_mod_df["sales_df"].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2935849 entries, 0 to 2935848
Data columns (total 14 columns):
 #   Column              Dtype
---  ------              -----
 0   date                datetime64[ns]
 1   date_block_num      int64
 2   shop_id             category
 3   item_id             category
 4   item_price          float64
 5   item_cnt_day        float64
 6   shop_name           category
 7   item_name           category
 8   item_category_id    category
 9   item_category_name  category
 10  market_category     object
 11  item_category       object
 12  year                int64
 13  month               int64
dtypes: category(6), datetime64[ns](1), float64(2), int64(3), object(2)
memory usage: 225.3+ MB

**Stratisfied sampling:**

Aplicar un muestreo estratificado basado en las diferentes categorias.
* item category
* market category
* Shop name
* item_cnt_day

In [14]:
dict_mod_df["sales_df"]["year"].value_counts()

2013    1267562
2014    1055861
2015     612426
Name: year, dtype: int64

In [35]:
# Building a training set and a test set based on a stratified sampling
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(dict_mod_df["sales_df"], dict_mod_df["sales_df"]["market_category"]):
    strat_train_set = dict_mod_df["sales_df"].loc[train_index]
    strat_test_set = dict_mod_df["sales_df"].loc[test_index]

In [43]:
# put the dataframes into a single data structure
dict_sales_df = {"strat_train_set":strat_train_set, 
                 "strat_test_set":strat_test_set,
                 "sales_df":dict_mod_df["sales_df"]}

Validation of the sampling data versus full data

In [75]:
# overall vs stratified sampling
overall = (dict_sales_df["sales_df"]["market_category"].value_counts() / len(dict_sales_df["sales_df"]["market_category"]) *100).to_frame() 
stratified = (dict_sales_df["strat_train_set"]["market_category"].value_counts() / len(dict_sales_df["strat_train_set"]["market_category"]) *100).to_frame()


ov_vs_strat = pd.concat({"overall":overall, "stratified":stratified},axis=1)
ov_vs_strat

                                            overall      stratified
                                    market_category market_category
Cinema                                    28.387564       28.387574
Games                                     17.833308       17.833301
PC Games                                  17.236445       17.236455
Music                                     13.688102       13.688120
Gifts                                     12.618156       12.618157
Accessories                                2.596796        2.596779
Books                                      2.364699        2.364691
Programs                                   2.221981        2.221972
Payment cards                              1.124411        1.124419
Game consoles                              0.843708        0.843708
Service                                    0.353969        0.353986
Batteries                                  0.245449        0.245457
Payment cards (Movie, Music, Games)        0.166051        0.166051
Blank media (piece)                        0.149531        0.149531
Delivery of goods                          0.074697        0.074680
Tickets (Digital)                          0.063934        0.063951
Pure media (spire)                         0.027079        0.027079
Android Games                              0.003100        0.003108
Payment Cards                              0.000647        0.000639
MAC Games                                  0.000272        0.000255
PC                                         0.000102        0.000085

In [ ]:
pd.Data

dict_keys(['sales_df', 'sales_df_raw', 'items_cat_df', 'items_df', 'items_df_sales', 'item_sales_distr', 'item_sales_distr_cnt', 'item_sales_shop', 'sales_shop', 'tsa_market_cat', 'pivot_tsa_market_cat', 'pivot_tsa_market_cat_%', 'tsa_shops', 'pivot_tsa_shops', 'sales_market_shop_year', 'pivot_sales_market_shop_year', 'tsa_markets_month', 'pivot_tsa_markets_month', 'tsa_markets_year'])